title: libreim

# theme: minima
baseurl: ""
assets_path: /assets

locale: "es"
permalink: pretty

markdown: kramdown
kramdown:
  parse_span_html: false
highlighter: rouge

plugins:
  - octopress-paginate
#  - jemoji
#  - jekyll-gist

pagination:
  per_page: 5
  limit: false
  permalink: /page/:num/
  title_suffix: ""

exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - deploy.sh
  - README.md

# Tag configuration
tag_dir: "/t"
tag_title_prefix: ""
tag_title_suffix: ""
category_collection: "blog"
category_dir: "/c"
category_title_prefix: ""
category_title_suffix: ""

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      side: true
  - scope:
      path: "_blog"
    values:
      layout: "post"
      side: true

collections:
  blog:
    output: true
